# Generated by Django 4.1.1 on 2022-09-14 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicimarketapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('bike_id', models.AutoField(primary_key=True, serialize=False)),
                ('bike_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('bike_category', models.CharField(max_length=25)),
                ('country', models.CharField(blank=True, max_length=25)),
                ('bike_image', models.CharField(max_length=150)),
                ('brand', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=15)),
                ('size_rin', models.CharField(blank=True, max_length=3)),
                ('size_frame', models.CharField(blank=True, max_length=3)),
                ('brake_system', models.CharField(max_length=25)),
                ('year', models.DateField(blank=True, null=True)),
                ('bike_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('stock', models.SmallIntegerField(default=1)),
                ('created_at', models.DateField(default=datetime.date.today, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
