# Generated by Django 4.1.1 on 2022-09-17 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bicimarketapp', '0002_bike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_cust_order', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fecha', models.DateField()),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_order', to='bicimarketapp.customers')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cantidad', models.SmallIntegerField(default=1)),
                ('customer_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicimarketapp.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicimarketapp.bike')),
            ],
        ),
    ]
